name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install toolchain
      run: rustup install x86_64-pc-windows-msvc
    - name: Build
      run: cargo build --target=x86_64-pc-windows-msvc --verbose --release
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: windows-build
        path: target\release\*.exe
